In [24]:
import pandas as pd
import pandas_datareader as web 
from config import API_KEY

In [30]:
ticker = 'NVDA'
nvda = web.get_data_tiingo(ticker, api_key = API_KEY)

In [31]:
nvda.head()

                                  close   high     low   open   volume  \
symbol date
NVDA   2016-04-18 00:00:00+00:00  36.97  37.06  36.610  37.06  7683044
       2016-04-19 00:00:00+00:00  36.31  37.18  36.080  37.11  7728777
       2016-04-20 00:00:00+00:00  36.45  36.67  36.210  36.25  5004434
       2016-04-21 00:00:00+00:00  36.41  36.63  36.250  36.46  4456989
       2016-04-22 00:00:00+00:00  36.27  36.78  36.145  36.53  5588539

                                   adjClose    adjHigh     adjLow    adjOpen  \
symbol date
NVDA   2016-04-18 00:00:00+00:00  36.296506  36.384867  35.943065  36.384867
       2016-04-19 00:00:00+00:00  35.648530  36.502681  35.422720  36.433956
       2016-04-20 00:00:00+00:00  35.785979  36.001971  35.550351  35.589623
       2016-04-21 00:00:00+00:00  35.746708  35.962700  35.589623  35.795797
       2016-04-22 00:00:00+00:00  35.609258  36.109968  35.486536  35.864522

                                  adjVolume  divCash  splitFactor
symbol date
NVDA   2016-04-18 00:00:00+00:00    7683044      0.0          1.0
       2016-04-19 00:00:00+00:00    7728777      0.0          1.0
       2016-04-20 00:00:00+00:00    5004434      0.0          1.0
       2016-04-21 00:00:00+00:00    4456989      0.0          1.0
       2016-04-22 00:00:00+00:00    5588539      0.0          1.0

In [32]:
nvda.to_csv('csv/nvidia.csv')